-- MySQL Script generated by MySQL Workbench
-- Tue Jul 25 00:22:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SIGEV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIGEV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIGEV` DEFAULT CHARACTER SET utf8 ;
USE `SIGEV` ;

-- -----------------------------------------------------
-- Table `SIGEV`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`rol` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idRol`),
  UNIQUE INDEX `nombreRol_UNIQUE` (`nombreRol` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`usuario` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` CHAR(64) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `codigoRecuperacion` VARCHAR(45) NULL,
  `estatusUsuario` TINYINT(1) NOT NULL DEFAULT 1,
  `rol_idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_rol1_idx` (`rol_idRol` ASC),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`rol_idRol`)
    REFERENCES `SIGEV`.`rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `SIGEV`.`rol_permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`rol_permiso` ;


-- -----------------------------------------------------
-- Table `SIGEV`.`permiso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`permiso` ;


-- -----------------------------------------------------
-- Table `SIGEV`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`persona` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombrePersona` VARCHAR(45) NOT NULL,
  `primerApellido` VARCHAR(45) NOT NULL,
  `segundoApellido` VARCHAR(45) NULL,
  `usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_persona_usuario1_idx` (`usuario_idUsuario` ASC),
  CONSTRAINT `fk_persona_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `SIGEV`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`voluntario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`voluntario` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`voluntario` (
  `idVoluntario` INT NOT NULL AUTO_INCREMENT,
  `curp` VARCHAR(18) NOT NULL,
  `estatusVoluntario` TINYINT(1) NOT NULL DEFAULT 1,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idVoluntario`),
  INDEX `fk_voluntario_persona1_idx` (`persona_idPersona` ASC),
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC),
  CONSTRAINT `fk_voluntario_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `SIGEV`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`color` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`color` (
  `idColor` INT NOT NULL AUTO_INCREMENT,
  `nombreColor` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idColor`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  UNIQUE INDEX `nombreColor_UNIQUE` (`nombreColor` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`organizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`organizacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`organizacion` (
  `idOrganizacion` INT NOT NULL AUTO_INCREMENT,
  `rfc` VARCHAR(13) NOT NULL,
  `nombreOrganizacion` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(100) NOT NULL,
  `imagenLogotipo` LONGTEXT NULL,
  `estatusOrganizacion` TINYINT(1) NOT NULL DEFAULT 1,
  `usuario_idUsuario` INT NOT NULL,
  `color_idColor` INT NOT NULL,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idOrganizacion`),
  INDEX `fk_organizacion_usuario1_idx` (`usuario_idUsuario` ASC),
  INDEX `fk_organizacion_color1_idx` (`color_idColor` ASC),
  INDEX `fk_organizacion_direccion1_idx` (`direccion_idDireccion` ASC),
  UNIQUE INDEX `rfc_UNIQUE` (`rfc` ASC),
  UNIQUE INDEX `razonSocial_UNIQUE` (`razonSocial` ASC),
  CONSTRAINT `fk_organizacion_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `SIGEV`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizacion_color1`
    FOREIGN KEY (`color_idColor`)
    REFERENCES `SIGEV`.`color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT `fk_organizacion_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `SIGEV`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`estado` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`direccion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `noExterior` VARCHAR(5) NOT NULL DEFAULT 'S/N',
  `noInterior` VARCHAR(5) NULL DEFAULT 'S/N',
  `estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_direccion_estado1_idx` (`estado_idEstado` ASC),
  CONSTRAINT `fk_direccion_estado1`
    FOREIGN KEY (`estado_idEstado`)
    REFERENCES `SIGEV`.`estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`evento` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombreEvento` VARCHAR(100) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `estatusEvento` TINYINT(1) NOT NULL DEFAULT 1,
  `direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_evento_direccion1_idx` (`direccion_idDireccion` ASC),
  CONSTRAINT `fk_evento_direccion1`
    FOREIGN KEY (`direccion_idDireccion`)
    REFERENCES `SIGEV`.`direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`voluntario_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`voluntario_evento` ;


-- -----------------------------------------------------
-- Table `SIGEV`.`notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`notificacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `mensaje` VARCHAR(250) NOT NULL,
  `estatusNotificacion` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`idNotificacion`))
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`voluntario_notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`voluntario_notificacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`voluntario_notificacion` (
  `voluntario_idVoluntario` INT NOT NULL,
  `notificacion_idNotificacion` INT NOT NULL,
  PRIMARY KEY (`voluntario_idVoluntario`, `notificacion_idNotificacion`),
  INDEX `fk_voluntario_has_notificacion_notificacion1_idx` (`notificacion_idNotificacion` ASC),
  INDEX `fk_voluntario_has_notificacion_voluntario1_idx` (`voluntario_idVoluntario` ASC),
  CONSTRAINT `fk_voluntario_has_notificacion_voluntario1`
    FOREIGN KEY (`voluntario_idVoluntario`)
    REFERENCES `SIGEV`.`voluntario` (`idVoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_has_notificacion_notificacion1`
    FOREIGN KEY (`notificacion_idNotificacion`)
    REFERENCES `SIGEV`.`notificacion` (`idNotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`notificacion_organizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`notificacion_organizacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`notificacion_organizacion` (
  `notificacion_idNotificacion` INT NOT NULL,
  `organizacion_idOrganizacion` INT NOT NULL,
  PRIMARY KEY (`notificacion_idNotificacion`, `organizacion_idOrganizacion`),
  INDEX `fk_notificacion_has_organizacion_organizacion1_idx` (`organizacion_idOrganizacion` ASC),
  INDEX `fk_notificacion_has_organizacion_notificacion1_idx` (`notificacion_idNotificacion` ASC),
  CONSTRAINT `fk_notificacion_has_organizacion_notificacion1`
    FOREIGN KEY (`notificacion_idNotificacion`)
    REFERENCES `SIGEV`.`notificacion` (`idNotificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notificacion_has_organizacion_organizacion1`
    FOREIGN KEY (`organizacion_idOrganizacion`)
    REFERENCES `SIGEV`.`organizacion` (`idOrganizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `SIGEV`.`organizacion_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`organizacion_evento` ;

-- -----------------------------------------------------
-- Table `SIGEV`.`evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`evaluacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`evaluacion` (
  `idEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `nombreEvaluacion` VARCHAR(45) NOT NULL,
  `fechaRegistro` DATETIME NOT NULL,
  `estatusEvaluacion` TINYINT(1) NOT NULL DEFAULT 1,
  `organizacion_idOrganizacion` INT NOT NULL,
  PRIMARY KEY (`idEvaluacion`),
  INDEX `fk_evaluacion_has_organizacion_idx` (`organizacion_idOrganizacion` ASC),
  CONSTRAINT `fk_evaluacion_has_organizacion_organizacion1`
      FOREIGN KEY (`organizacion_idOrganizacion`)
      REFERENCES `SIGEV`.`organizacion` (`idOrganizacion`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGEV`.`pregunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`pregunta` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`pregunta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `textoPregunta` VARCHAR(250) NOT NULL,
  `evaluacion_idEvaluacion` INT NOT NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `fk_pregunta_evaluacion1_idx` (`evaluacion_idEvaluacion` ASC),
  CONSTRAINT `fk_pregunta_evaluacion1`
    FOREIGN KEY (`evaluacion_idEvaluacion`)
    REFERENCES `SIGEV`.`evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGEV`.`evaluacion_organizacion_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`evaluacion_organizacion_evento` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`evaluacion_organizacion_evento` (
  `idEvaluacionOrganizacionEvento` INT NOT NULL AUTO_INCREMENT,
  `evaluacion_idEvaluacion` INT NOT NULL,
  `organizacion_idOrganizacion` INT NOT NULL,
  `evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idEvaluacionOrganizacionEvento`),
  INDEX `fk_organizacionEvaluacion_organizacion1_idx` (`organizacion_idOrganizacion` ASC),
  INDEX `fk_organizacionEvaluacion_evaluacion1_idx` (`evaluacion_idEvaluacion` ASC),
  INDEX `fk_organizacionEvaluacion_evento1_idx` (`evento_idEvento` ASC),
  CONSTRAINT `fk_organizacionEvaluacion_organizacion1`
    FOREIGN KEY (`organizacion_idOrganizacion`)
    REFERENCES `SIGEV`.`organizacion` (`idOrganizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizacionEvaluacion_evaluacion1`
    FOREIGN KEY (`evaluacion_idEvaluacion`)
    REFERENCES `SIGEV`.`evaluacion` (`idEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_organizacionEvaluacion_evento1`
    FOREIGN KEY (`evento_idEvento`)
    REFERENCES `SIGEV`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGEV`.`voluntario_evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`voluntario_evaluacion` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`voluntario_evaluacion` (
  `idVoluntarioEvaluacion` INT NOT NULL AUTO_INCREMENT,
  `voluntario_idVoluntario` INT NOT NULL,
  `estatusVoluntarioEvaluacion` TINYINT(1) NOT NULL DEFAULT 1,
  `evaluacion_organizacion_evento_idEvaluacionOrganizacionEvento` INT NOT NULL,
  PRIMARY KEY (`idVoluntarioEvaluacion`),
  INDEX `fk_voluntario_respuesta_evaluacion_voluntario1__idx` (`voluntario_idVoluntario` ASC),
  INDEX `fk_voluntario_respuesta_evaluacion_evaluacion_organizacion__idx` (`evaluacion_organizacion_evento_idEvaluacionOrganizacionEvento` ASC),
  CONSTRAINT `fk_voluntario_respuesta_evaluacion__voluntario1`
    FOREIGN KEY (`voluntario_idVoluntario`)
    REFERENCES `SIGEV`.`voluntario` (`idVoluntario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_voluntario_respuesta_evaluacion__evaluacion_organizacion_ev1`
    FOREIGN KEY (`evaluacion_organizacion_evento_idEvaluacionOrganizacionEvento`)
    REFERENCES `SIGEV`.`evaluacion_organizacion_evento` (`idEvaluacionOrganizacionEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SIGEV`.`respuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SIGEV`.`respuesta` ;

CREATE TABLE IF NOT EXISTS `SIGEV`.`respuesta` (
  `idRespuesta` INT NOT NULL AUTO_INCREMENT,
  `textoRespuesta` TEXT NOT NULL,
  `pregunta_idPregunta` INT NOT NULL,
  `voluntario_evaluacion_idVoluntarioEvaluacion` INT NOT NULL,
  PRIMARY KEY (`idRespuesta`),
  INDEX `fk_respuesta_pregunta1_idx` (`pregunta_idPregunta` ASC),
  INDEX `fk_respuesta_voluntario_evaluacion1_idx` (`voluntario_evaluacion_idVoluntarioEvaluacion` ASC),
  CONSTRAINT `fk_respuesta_pregunta1`
    FOREIGN KEY (`pregunta_idPregunta`)
    REFERENCES `SIGEV`.`pregunta` (`idPregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_respuesta_voluntario_evaluacion1`
    FOREIGN KEY (`voluntario_evaluacion_idVoluntarioEvaluacion`)
    REFERENCES `SIGEV`.`voluntario_evaluacion` (`idVoluntarioEvaluacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
